### ISSUE TITLE
return url redirection is returning a not encoded url

### ISSUE THREAD

**Issue by epgeroy** [dlocal/smart-fields-examples#13]
Hi there

I'm sending an encoded url, but the url I'm receiving back is not encoded, so the redirection is not working, I managed to do a workaround but I would like to receive the url encoded back.

Thxs and awesome product :)

**Comment by gimena-bernadet** [comment]
Hi! sorry for the delay, where are you sending the encoded url? are you talking about dlocal integration or smart-fields?

**Comment by epgeroy** [comment]
thank you, I wont be using your product anymore
